### ISSUE TITLE
fix gruntfile.js

### ISSUE THREAD

**Issue by skeep** [skeep/v-nova#1]
- [x] watch should be the last task
- [x] connect.base is wrong ... we dont have 'www-root' folder
- [x] jade task ... we need to run jade for all file under /views as well
- [x] less task is not for script but stylesheet, fix the folder plz
- [x] use 'usemin' instead of seperate uglify task

**Comment by kakulgupta** [comment]
fixed these issues

**Comment by skeep** [comment]
closing it
